### ISSUE TITLE
Containers don't see each other in cross-peer environment

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/subos#110]
There is a problem with containers in cross-peer environment: they are not accessible to each other. Sometimes a container doesn't see its gateway too: 192.168.1.1.

Testing environment: 
* One physical machine with two virtual RH. 
* RHs get IP from a wifi router.
* Each RH has management.
* RHs are created with: (1) autobuild -v -t 201 (2) autobuild -v -t 202.

**Comment by soffokl** [comment]
Fixed by new MESH topology.
