### ISSUE TITLE
Feedback from import during download and import phase would be nice

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#144]
![image](https://cloud.githubusercontent.com/assets/10051386/14129426/12365dde-f5f8-11e5-8021-e43661fe43ec.png)

While downloading and importing after the download it would be nice to show some progress in this process. Now that we have content length available from Kurjun we can actually show download progress based on the percentage of the file already pulled down. This can also be used by the agent to send back information to SS about progress which can give better feedback to the user.

**Comment by soffokl** [comment]
Duplicate for: https://github.com/subutai-io/base/issues/388

**Comment by soffokl** [comment]
![screenshot from 2016-03-31 15-40-17](https://cloud.githubusercontent.com/assets/8612618/14171887/1dadac2a-f757-11e5-9c59-edc08c881bba.png)
