### ISSUE TITLE
Upgrade to ubuntu snappy 16.04

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#248]

**Comment by soffokl** [comment]
Finally we have 16.04 images: http://cdimage.ubuntu.com/ubuntu-snappy/16.04/current/
But first start of this images was changed a lot. Now it's provides kind of wizard for first configuration:
![image](https://cloud.githubusercontent.com/assets/8612618/18425107/58255788-78d8-11e6-9762-702b689c98a8.png)
Biggest problem of this configuration for us - it require ubuntu.com account to create first user in the system:
![image](https://cloud.githubusercontent.com/assets/8612618/18425123/7ec9847c-78d8-11e6-8fe9-0a93b4011f5a.png)
This user should have configured ssh-keys in the profile:
![image](https://cloud.githubusercontent.com/assets/8612618/18425130/950aab9e-78d8-11e6-9eed-fe192f81cfcb.png)

So it looks like it's very difficult now configure automated installation using this system.

**Comment by tzununbekov** [comment]
Looks like it is temporary issue for beta images. Here is IRC quotation:

>  <tzununbekov> mvo, hey! Could you help me with Ubuntu Snappy 16.04? Trying to figure out if it is required now to have Ubuntu One account to use Snappy
> <mvo> tzununbekov: this is the case right now, we are working on local users that are created differently, but the current image needs a u1 account  that is used to setup your local user. the upside is that this is super convinient, i.e. your ssh keys are on the device, your prefered username and we plan to sync the ssh keys in the future so that key update will be totally transparent

**Comment by akarasulu** [comment]
Let's modify this code so it works with our Hub. Should be easy to do I think?

**Comment by soffokl** [comment]
github.com/subutai-io/snap
