### ISSUE TITLE
Upgrade all templates to use new 16.04 based master ubuntu template

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#250]

**Comment by soffokl** [comment]
We need to not just update base image for all templates, but keep updating version of products that we are using for templates. Most of our templates like hadoop and cassandra are outdated, and we need to include latest versions of these products.

**Comment by akarasulu** [comment]
@eabyshev This will impact the plugins and all the templates so this is something you'll have to do instead of sysnet. @soffokl please provide support for @eabyshev.
