### ISSUE TITLE
When importing appscale we do not see the download progress immediately

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#255]
The download progress delay is probably due to going out to external standalone Kurjun for the template, but then we see the progress occur, however it is very fast obviously because we're now pull down from local kurjun from subutai cli command.

This does not seem to be happening with the other templates or maybe I am not noticing it. There should be a way for us to consistently track download progress even if being downloaded from standalone by our internal nginx proxy.

**Comment by soffokl** [comment]
The problem here that kurjun does not starting send content until download full file. It just hold session without sending content size or data. 
Kurjun should start proxying content during download, like nginx do.

**Comment by akarasulu** [comment]
Embedded Kurjun right? It should start then.

**Comment by soffokl** [comment]
Both Kurjuns. But since we have only single standalone, you never face this problem with it.

**Comment by TalasZh** [comment]
fix introduced with embedded kurjun in subutai-io/base#818
