### ISSUE TITLE
Interfaces from deleted environments seem to remain orphaned

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#273]
In the monitoring UI we see a number of environment interfaces:

![screen shot 2016-04-25 at 1 26 16 pm](https://cloud.githubusercontent.com/assets/10051386/14792852/3fbd0e90-0aea-11e6-8133-b4f77b2bb54c.png)

As you can see there are about 7 different environment p2p interfaces present with some gateways. But when you look at the environments there's just one environment visible:

![screen shot 2016-04-25 at 1 26 34 pm](https://cloud.githubusercontent.com/assets/10051386/14792879/66ad38a4-0aea-11e6-982f-3e03fdbfdafc.png)
 
Here's the "About" page on the peer. Note that this was @NikolaiB's peer which I just snuck into just now 🎱 :

![screen shot 2016-04-25 at 1 26 44 pm](https://cloud.githubusercontent.com/assets/10051386/14792904/8ec113d8-0aea-11e6-9c7c-d9aee9ab368c.png)

**Comment by soffokl** [comment]
Fixed here: https://github.com/subutai-io/subos/commit/3a99e14869425c5553af5851d4f53d2849671cea
