### ISSUE TITLE
Support both NAT and bridged networking to accommodate all scenarios.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#308]
This is something that we need to work on all together and will impact the installer people as well: @Lezh1k @btemir @p1gmale0n @soffokl @tzununbekov @crioto.

Here's the general situation:

VirtualBox has various issues with the MAC address it exposes over WiFi to enable bridged mode to get a DHCP lease. This makes it so **MOST** WiFi networks do not support our current configuration: hotels, conferences, and other public networks. The VM networking should be setup to support both NAT and bridged making the right decision at install time **AND** there after to account for users roaming from network to network. This capability needs to be built into our product. 

Some of this functionality around intelligent VM networking needs to be outside of the VM guest and can be handled by the tray. The VM guest needs to know what environment it's sitting in too. We need a robust situation that handles all changes and all scenarios. 

There might also be an impact on p2p and p2p might also do somethings for us with UPnP. **Please make sure to have a general online discussion about this topic and post the conclusions here. **

**Comment by soffokl** [comment]
done
