### ISSUE TITLE
Can not add reverse proxy.

### ISSUE THREAD

**Issue by eabyshev** [subutai-io/subos#363]
Steps to reproduce:

1) Create Appscale environment with 1 container
2) Go to RH
3)  grep vlan /mnt/lib/lxc/container_name/config
4) sudo subutai proxy del 'vlan_id'

```
(amd64)ubuntu@rh1464247688:~$ grep vlan /mnt/lib/lxc/483a9a87-6961-42f1-b3c9-0484effd253b/config 
#vlan_id = 104
(amd64)ubuntu@rh1464247688:~$ sudo subutai proxy del 104
```

the same error appear when trying execute sudo subutai proxy add 104 -h container_name

**Comment by soffokl** [comment]
Not reproducible.
