### ISSUE TITLE
Containers on remote peer are not accessible

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/subos#364]
Steps:
1. Register two peers to each other. Peers are not within LAN, and not registered to Hub.
2. Create environment using these peers: 4 containers based on the master template; 2 containers on each peer. 
3. Check ping from each container to other ones. 

Result:
1. Ping is successful to a container on same peer only.
2. Containers on remote peer are not accessible. 

SS version: 
- Commit ID: aeb32b52d00d78e965c87d63040c405e5df49e77
- SS version: 4.0.0-RC13-SNAPSHOT
- RH version: 4.0.0-RC13
- P2P version: 4.0.0-RC12. Packet version: 4

Notes: 
* I could reproduce using AWS hosted peers: Ireland, Germany, California, Virginia. Tested between all of them and reproduces.
* The bug may be reproducible with home peers too, if they are not in LAN. But I am not sure b/c I could not test that. (Don't have peers accessible directly to each other).
* I guess, this bug was introduced somewhere in last month. I tested same scenario in April when was working with AppScale cluster. Then connection was OK to remote containers.

**Comment by asanaliev** [comment]
For some time ping to a remote container started giving this: 
root@7955302a-5241-401c-851e-88b182455db8:/# ping 172.16.60.2
PING 172.16.60.2 (172.16.60.2) 56(84) bytes of data.
64 bytes from 172.16.60.2: icmp_seq=1 ttl=64 time=235 ms
64 bytes from 172.16.60.2: icmp_seq=1 ttl=64 time=235 ms (DUP!)
64 bytes from 172.16.60.2: icmp_seq=1 ttl=64 time=235 ms (DUP!)
64 bytes from 172.16.60.2: icmp_seq=1 ttl=64 time=235 ms (DUP!)
64 bytes from 172.16.60.2: icmp_seq=2 ttl=64 time=241 ms
64 bytes from 172.16.60.2: icmp_seq=2 ttl=64 time=241 ms (DUP!)
64 bytes from 172.16.60.2: icmp_seq=2 ttl=64 time=241 ms (DUP!)
64 bytes from 172.16.60.2: icmp_seq=2 ttl=64 time=241 ms (DUP!)
64 bytes from 172.16.60.2: icmp_seq=3 ttl=64 time=239 ms
64 bytes from 172.16.60.2: icmp_seq=3 ttl=64 time=239 ms (DUP!)
64 bytes from 172.16.60.2: icmp_seq=3 ttl=64 time=239 ms (DUP!)
64 bytes from 172.16.60.2: icmp_seq=3 ttl=64 time=239 ms (DUP!)

But soon again ping failed:
root@7955302a-5241-401c-851e-88b182455db8:/# ping 172.16.60.3
PING 172.16.60.3 (172.16.60.3) 56(84) bytes of data.
From 172.16.60.5 icmp_seq=1 Destination Host Unreachable
From 172.16.60.5 icmp_seq=2 Destination Host Unreachable
From 172.16.60.5 icmp_seq=3 Destination Host Unreachable

**Comment by soffokl** [comment]
Tested crosspeer environment based on master template. 
4 containers, 2 peers. All containers can ping each other, and sshable.
@asanaliev do you using any special installation? 
![image](https://cloud.githubusercontent.com/assets/8612618/15732700/2c278afc-28a1-11e6-8d36-e1e15b299ed9.png)
![image](https://cloud.githubusercontent.com/assets/8612618/15732721/4b044ba4-28a1-11e6-9dc2-65a7e63976b5.png)
![image](https://cloud.githubusercontent.com/assets/8612618/15732738/847b265a-28a1-11e6-86f9-4a68c17cd25d.png)
![image](https://cloud.githubusercontent.com/assets/8612618/15732744/93552cc0-28a1-11e6-9151-a4cca778f93c.png)

**Comment by soffokl** [comment]
Checked with 2 peers behind NAT, remote p2p is not accessible. 
![image](https://cloud.githubusercontent.com/assets/8612618/15733389/53deae1c-28a7-11e6-84e8-1d18b1e909b2.png)

@crioto looks like some problem with proxying traffic.

**Comment by soffokl** [comment]
```
(amd64)root@rh1464838045:~# /apps/subutai/current/bin/p2p debug
DEBUG INFO:
Number of gouroutines: 29
Instances information:
Hash: swarm-fb932360-3dbf-4282-b0b4-662fcd7b707e
ID: 30cc9bdc-2875-11e6-8310-022d0fae0f03
Interface p2p100, HW Addr: 06:f2:9e:eb:51:49, IP: 10.253.182.4
Peers:
	--- 30cc85cf-2875-11e6-8c19-022d0fae0f03 ---
		HWAddr: 06:72:2f:25:a6:e3
		IP: 10.253.182.3
		Endpoint: 192.168.56.103:38778
		Peer Address: 192.168.56.103:38778
		Proxy ID: 0
	--- End of 30cc85cf-2875-11e6-8c19-022d0fae0f03 ---

(amd64)root@rh1464838045:~# 
```
```
(amd64)root@rh1464837875:~# /apps/subutai/current/bin/p2p debug
DEBUG INFO:
Number of gouroutines: 29
Instances information:
Hash: swarm-fb932360-3dbf-4282-b0b4-662fcd7b707e
ID: 30cc85cf-2875-11e6-8c19-022d0fae0f03
Interface p2p100, HW Addr: 06:72:2f:25:a6:e3, IP: 10.253.182.3
Peers:
	--- 30cc9bdc-2875-11e6-8310-022d0fae0f03 ---
		HWAddr: 06:f2:9e:eb:51:49
		IP: 10.253.182.4
		Endpoint: 192.168.56.104:33312
		Peer Address: 192.168.56.104:33312
		Proxy ID: 0
	--- End of 30cc9bdc-2875-11e6-8310-022d0fae0f03 ---

(amd64)root@rh1464837875:~# 
```

**Comment by tzununbekov** [comment]
Remote RH1:

`(amd64)root@rh1464838774:~# ifconfig p2p100
p2p100    Link encap:Ethernet  HWaddr 06:08:1b:c6:81:27  
          inet addr:10.253.182.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::2485:1aff:fee8:b730/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1600  Metric:1
          RX packets:37 errors:0 dropped:0 overruns:0 frame:0
          TX packets:536 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:3488 (3.4 KB)  TX bytes:30096 (30.0 KB)

(amd64)root@rh1464838774:~# 
(amd64)root@rh1464838774:~# /apps/subutai/current/bin/p2p debug
DEBUG INFO:
Number of gouroutines: 22
Instances information:
Hash: swarm-fb932360-3dbf-4282-b0b4-662fcd7b707e
ID: 1caa014a-287b-11e6-85b6-022d0fae0f03
Interface p2p100, HW Addr: 06:08:1b:c6:81:27, IP: 10.253.182.1
Peers:
	--- 1c84d103-287b-11e6-8c47-022d0fae0f03 ---
		HWAddr: 06:af:8a:f6:16:19
		IP: 10.253.182.2
		Endpoint: 192.168.56.163:60376
		Peer Address: 192.168.56.163:60376
		Proxy ID: 0
	--- End of 1c84d103-287b-11e6-8c47-022d0fae0f03 ---

(amd64)root@rh1464838774:~# 
`
[rh1.txt](https://github.com/subutai-io/subos/files/294819/rh1.txt)

**Comment by tzununbekov** [comment]
Remote RH2:
```
(amd64)root@rh1464838900:~# ifconfig p2p100
p2p100    Link encap:Ethernet  HWaddr 06:af:8a:f6:16:19  
          inet addr:10.253.182.2  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::60fe:11ff:fefd:49f5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1600  Metric:1
          RX packets:523 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5983 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:53430 (53.4 KB)  TX bytes:257285 (257.2 KB)

(amd64)root@rh1464838900:~# 
(amd64)root@rh1464838900:~# /apps/subutai/current/bin/p2p debug
DEBUG INFO:
Number of gouroutines: 29
Instances information:
Hash: swarm-fb932360-3dbf-4282-b0b4-662fcd7b707e
ID: 1c84d103-287b-11e6-8c47-022d0fae0f03
Interface p2p100, HW Addr: 06:af:8a:f6:16:19, IP: 10.253.182.2
Peers:
	--- 1caa014a-287b-11e6-85b6-022d0fae0f03 ---
		HWAddr: 06:08:1b:c6:81:27
		IP: 10.253.182.1
		Endpoint: 192.168.56.162:35034
		Peer Address: 192.168.56.162:35034
		Proxy ID: 0
	--- End of 1caa014a-287b-11e6-85b6-022d0fae0f03 ---

(amd64)root@rh1464838900:~# 
```
[rh2.txt](https://github.com/subutai-io/subos/files/294820/rh2.txt)

**Comment by crioto** [comment]
Fixed binary in dev

**Comment by soffokl** [comment]
Checked both LAN and NAT cases, works fine. 
Tested with switching ISP, after few minutes all containers can ping each other and ssh works between all container.

**Comment by asanaliev** [comment]
I could reproduce this issues again. Tested with home and hosted peers. Containers over WAN can't ping each other.

===
**Home peers**
My peer: https://hub.subut.ai/peers/AE8D5C2145034E8792A8D562BB98A77E9045F164
![image](https://cloud.githubusercontent.com/assets/7465404/15976305/b92b1d6e-2f73-11e6-975f-2c7d698dc758.png)

Sydyk: https://hub.subut.ai/peers/C537F8993EF5E96F7ECFC3B8F1CCD252B4EE35BA
![image](https://cloud.githubusercontent.com/assets/7465404/15976297/a79c9ea6-2f73-11e6-81e0-46aff4c55ba8.png)

===
**Hosted peers**
AWS Ireland: https://hub.subut.ai/peers/BE2DF9AFE71C91AAEA4F2EE7015995B7D7E78857
![image](https://cloud.githubusercontent.com/assets/7465404/15976338/ebd76588-2f73-11e6-9204-39d7b6f45ab9.png)

Google US: https://hub.subut.ai/peers/8DBC59E404F1C9E3B71C27AD337A680B402FF6DA
![image](https://cloud.githubusercontent.com/assets/7465404/15976350/02ea66f8-2f74-11e6-821b-7274b2b3cc16.png)

**Comment by Dilshat** [comment]
@asanaliev please retest and close if fixed

**Comment by asanaliev** [comment]
I created env over six peers: 

![image](https://cloud.githubusercontent.com/assets/7465404/16018176/2215dba4-31c5-11e6-88dc-18cb45d283fa.png)

Each of peer has latest updates (RH/SS):

![image](https://cloud.githubusercontent.com/assets/7465404/16018163/10429462-31c5-11e6-95b3-78876ceb6381.png)

Ping is accessible between all containers except AWS peers. In other words, AWS US and AWS Ireland don't see other peers, and other peers don't see them too.

**Comment by asanaliev** [comment]
Created env between these three peers:
![image](https://cloud.githubusercontent.com/assets/7465404/16036006/c71a77d8-323b-11e6-84db-4e242514b8bc.png)

Peer 107 and Google EU see each other but don't AWS Ireland. Attached logs:

[107-p2p-log.txt](https://github.com/subutai-io/subos/files/313436/107-p2p-log.txt)
[google-eu-p2p-log.txt](https://github.com/subutai-io/subos/files/313443/google-eu-p2p-log.txt)
[aws-ireland-p2p-log.txt](https://github.com/subutai-io/subos/files/313438/aws-ireland-p2p-log.txt)

Strange but no logs for AWS Ireland. 

**p2p debug**
Peer 107
```
(amd64)ubuntu@rh1465827537:~$ /apps/subutai/current/bin/p2p debug
DEBUG INFO:
Number of gouroutines: 128
Instances information:
Hash: swarm-b7d15d1f-68eb-4cd0-9ceb-9d4a0a9cf191
ID: 27c43844-3209-11e6-8cdf-022d0fae0f03
Interface p2p100, HW Addr: 06:29:49:74:e1:a2, IP: 10.119.171.2
Peers:
Hash: swarm-312e754d-b818-4c0c-9639-c4bc055182bf
ID: 27c4c528-3209-11e6-812e-022d0fae0f03
Interface p2p101, HW Addr: 06:c0:96:10:0b:7b, IP: 10.141.198.5
Peers:
	--- 04c02aff-3209-11e6-899e-022d0fae0f03 ---
		HWAddr: 06:8f:f0:97:91:1b
		IP: 10.141.198.3
		Endpoint: 54.93.222.10:54644
		Peer Address: 104.197.249.240:36734
		Proxy ID: 34
	--- End of 04c02aff-3209-11e6-899e-022d0fae0f03 ---
Hash: swarm-cd235a1c-721c-42b2-a661-49238216b417
ID: 27901311-3209-11e6-8895-022d0fae0f03
Interface p2p102, HW Addr: 06:03:8b:06:c0:14, IP: 10.220.30.3
Peers:
Hash: swarm-fb22a6b3-5a8c-4018-aaf4-eedee2b8bf4f
ID: 27fe5d6d-3209-11e6-888c-022d0fae0f03
Interface p2p103, HW Addr: 06:eb:63:de:9c:68, IP: 10.171.210.3
Peers:
	--- 0525b943-3209-11e6-890a-022d0fae0f03 ---
		HWAddr: 06:eb:d2:06:f5:bb
		IP: 10.171.210.1
		Endpoint: 54.93.222.10:54644
		Peer Address: 104.155.117.207:54211
		Proxy ID: 40
	--- End of 0525b943-3209-11e6-890a-022d0fae0f03 ---
```

Google EU
```
(amd64)ubuntu@rh1455901999:~$ /apps/subutai/current/bin/p2p debug
DEBUG INFO:
Number of gouroutines: 69
Instances information:
Hash: ce1d601d39563011ca150d5b985a135f
ID: 3cf30c9d-3204-11e6-8dad-022d0fae0f03
Interface p2p102, HW Addr: 06:53:f5:17:a5:c3, IP: 10.174.178.3
Peers:
	--- 3d0b312c-3204-11e6-81d6-022d0fae0f03 ---
		HWAddr: 06:bc:79:76:34:29
		IP: 10.174.178.7
		Endpoint: 10.215.76.7:49176
		Peer Address: 10.215.76.7:49176
		Proxy ID: 0
	--- End of 3d0b312c-3204-11e6-81d6-022d0fae0f03 ---
Hash: ed71231bdc2e9e96ab18aab3a5eb9768
ID: 266cff1c-31b9-11e6-89f0-022d0fae0f03
Interface p2p103, HW Addr: 06:d4:d2:c7:33:f1, IP: 10.215.76.3
Peers:
	--- 2fecbf78-31b9-11e6-8035-022d0fae0f03 ---
		HWAddr: 06:10:d1:23:55:e6
		IP: 10.215.76.7
		Endpoint: 54.93.222.10:54644
		Peer Address: 104.197.249.240:47210
		Proxy ID: 59
	--- End of 2fecbf78-31b9-11e6-8035-022d0fae0f03 ---
Hash: 0ffce4c5cebae68cb39f583f5751bbe4
ID: 40b26850-3204-11e6-8ea3-022d0fae0f03
Interface p2p100, HW Addr: 06:42:2b:0d:dc:e3, IP: 10.98.28.1
Peers:
Hash: 87b880f1df358ae9de054ea1bef7ed3c
ID: 917c6b16-3204-11e6-83ea-022d0fae0f03
Interface p2p101, HW Addr: 06:6e:6b:4e:0b:ef, IP: 10.172.29.3
Peers:
	--- 8a5a145b-3204-11e6-810f-022d0fae0f03 ---
		HWAddr: 06:18:1e:37:26:23
		IP: 10.172.29.7
		Endpoint: 10.215.76.7:57230
		Peer Address: 10.215.76.7:57230
		Proxy ID: 0
	--- End of 8a5a145b-3204-11e6-810f-022d0fae0f03 ---
Hash: swarm-fb22a6b3-5a8c-4018-aaf4-eedee2b8bf4f
ID: 0525b943-3209-11e6-890a-022d0fae0f03
Interface p2p104, HW Addr: 06:eb:d2:06:f5:bb, IP: 10.171.210.1
Peers:
	--- 27fe5d6d-3209-11e6-888c-022d0fae0f03 ---
		HWAddr: 06:eb:63:de:9c:68
		IP: 10.171.210.3
		Endpoint: 54.93.222.10:54644
		Peer Address: 212.112.126.174:60839
		Proxy ID: 38
	--- End of 27fe5d6d-3209-11e6-888c-022d0fae0f03 ---
```

AWS Ireland
```
(amd64)ubuntu@rh1462684159:~$ /apps/subutai/current/bin/p2p debug
DEBUG INFO:
Number of gouroutines: 215
Instances information:
Hash: swarm-12f42a29-60df-4599-9850-690223fa942e
ID: e7892168-3175-11e6-82b0-022d0fae0f03
Interface p2p117, HW Addr: 06:ed:60:d6:36:d0, IP: 10.215.104.2
Peers:
	--- e0aaef45-3175-11e6-8e83-022d0fae0f03 ---
		HWAddr: 06:90:f7:65:47:9e
		IP: 10.215.104.1
		Endpoint: 10.72.103.1:40960
		Peer Address: 10.72.103.1:40960
		Proxy ID: 0
	--- End of e0aaef45-3175-11e6-8e83-022d0fae0f03 ---
Hash: 32e4f956d0ce81128bb7eb3d9054885a
ID: 4e64150c-31b9-11e6-824e-022d0fae0f03
Interface p2p105, HW Addr: 06:7b:2e:49:66:13, IP: 10.203.234.1
Peers:
	--- 4e4cf763-31b9-11e6-8267-022d0fae0f03 ---
		HWAddr: 06:c3:f9:71:9f:11
		IP: 10.203.234.5
		Endpoint: 10.49.137.2:48251
		Peer Address: 10.49.137.2:48251
		Proxy ID: 0
	--- End of 4e4cf763-31b9-11e6-8267-022d0fae0f03 ---
Hash: swarm-fb22a6b3-5a8c-4018-aaf4-eedee2b8bf4f
ID: 0522e4fe-3209-11e6-8e91-022d0fae0f03
Interface p2p118, HW Addr: 06:dc:0a:29:68:48, IP: 10.171.210.2
Peers:
Hash: 6cf0426df3aafdcf80e6b956fc19d306
ID: 4e372b22-31b9-11e6-8917-022d0fae0f03
Interface p2p109, HW Addr: 06:6c:df:ff:06:ba, IP: 10.250.211.1
Peers:
Hash: 6805049f0dd760442ee8c304a4ca8c8c
ID: e09b31f5-3175-11e6-843d-022d0fae0f03
Interface p2p111, HW Addr: 06:a7:80:fa:34:71, IP: 10.185.62.1
Peers:
Hash: 0123932922c6dedb4597f6162b33dd14
ID: 4e3755c2-31b9-11e6-82ab-022d0fae0f03
Interface p2p103, HW Addr: 06:7c:2c:de:d2:d6, IP: 10.188.111.1
Peers:
Hash: swarm-ad628a7d-3ea9-4977-911d-2e7bc5b5ccdd
ID: e76830d9-3175-11e6-88eb-022d0fae0f03
Interface p2p113, HW Addr: 06:ff:53:ef:cd:5d, IP: 10.201.240.1
Peers:
Hash: swarm-1e688b1d-e9c0-4a12-a92f-0c54da6003e8
ID: e0ca8ccb-3175-11e6-81bd-022d0fae0f03
Interface p2p114, HW Addr: 06:17:28:1f:45:2e, IP: 10.180.185.1
Peers:
Hash: 8843b34152f08d4db2f4425f50b16d39
ID: 4e4955f2-31b9-11e6-8a53-022d0fae0f03
Interface p2p104, HW Addr: 06:33:8e:d2:ca:ea, IP: 10.155.188.1
Peers:
Hash: 7cafcf04b107b01ae6679e57667e1cb3
ID: 4ddf20e5-31b9-11e6-821f-022d0fae0f03
Interface p2p107, HW Addr: 06:60:e9:ea:a0:59, IP: 10.232.57.1
Peers:
Hash: c81062859832e9b81b3624af1b070e8b
ID: 4e49707b-31b9-11e6-853f-022d0fae0f03
Interface p2p102, HW Addr: 06:2b:68:58:0c:b1, IP: 10.49.137.1
Peers:
	--- 4e45d1fb-31b9-11e6-8795-022d0fae0f03 ---
		HWAddr: 06:7e:fc:e7:19:cb
		IP: 10.49.137.2
		Endpoint: 54.93.164.238:50466
		Peer Address: 52.53.223.165:57044
		Proxy ID: 11
	--- End of 4e45d1fb-31b9-11e6-8795-022d0fae0f03 ---
Hash: aa4b9c01db1757e0619285bd0074ebbd
ID: 4ddee514-31b9-11e6-812f-022d0fae0f03
Interface p2p106, HW Addr: 06:57:2e:5d:cd:cc, IP: 10.239.5.1
Peers:
Hash: swarm-a768c19c-463f-4326-8ed9-a5aceab1b285
ID: e04d6f03-3175-11e6-8b89-022d0fae0f03
Interface p2p100, HW Addr: 06:c4:ed:38:09:21, IP: 10.117.127.1
Peers:
Hash: 4dc1e16f37e28d2c30f94b9c078c0759
ID: 4e1e9cc2-31b9-11e6-8795-022d0fae0f03
Interface p2p101, HW Addr: 06:a1:92:7d:fd:d7, IP: 10.141.243.1
Peers:
	--- 4dc20288-31b9-11e6-8b0d-022d0fae0f03 ---
		HWAddr: 06:59:eb:95:11:e2
		IP: 10.141.243.2
		Endpoint: 10.49.137.2:47937
		Peer Address: 10.49.137.2:47937
		Proxy ID: 0
	--- End of 4dc20288-31b9-11e6-8b0d-022d0fae0f03 ---
Hash: swarm-e41c3204-94be-4694-a4a7-9abfdd7c1f5c
ID: e4177a3c-3175-11e6-8792-022d0fae0f03
Interface p2p115, HW Addr: 06:c4:eb:ef:95:98, IP: 10.28.48.2
Peers:
	--- e0d03f79-3175-11e6-8b82-022d0fae0f03 ---
		HWAddr: 06:5f:04:f4:29:59
		IP: 10.28.48.1
		Endpoint: 54.93.222.10:54644
		Peer Address: 54.93.50.170:54574
		Proxy ID: 49
	--- End of e0d03f79-3175-11e6-8b82-022d0fae0f03 ---
Hash: swarm-563d8a9d-7836-4c0c-9571-e2c3162ec069
ID: e0b809d8-3175-11e6-812b-022d0fae0f03
Interface p2p116, HW Addr: 06:fd:0e:b0:65:82, IP: 10.72.103.2
Peers:
	--- e0d081ea-3175-11e6-86a5-022d0fae0f03 ---
		HWAddr: 06:83:ee:2f:74:d5
		IP: 10.72.103.1
		Endpoint: 54.93.164.238:50466
		Peer Address: 54.93.50.170:44653
		Proxy ID: 17
	--- End of e0d081ea-3175-11e6-86a5-022d0fae0f03 ---
Hash: 985496a4e82bebdd8dfda885b1e48a1a
ID: 4e371906-31b9-11e6-8adc-022d0fae0f03
Interface p2p110, HW Addr: 06:80:bb:d6:27:45, IP: 10.108.113.1
Peers:
Hash: 8d50893d4025a01e3b8ca4d1f77388c4
ID: e0b28eb6-3175-11e6-8ab8-022d0fae0f03
Interface p2p112, HW Addr: 06:5c:ad:c6:54:fb, IP: 10.227.142.6
Peers:
Hash: f68a7a7fb5cad0de3b5da388f9c9c63b
ID: 4df9a19e-31b9-11e6-8e18-022d0fae0f03
Interface p2p108, HW Addr: 06:06:06:1b:ef:af, IP: 10.182.9.1
Peers:
```
===
@crioto You may ask @p1gmale0n to add you SSH key to those servers (AWS, Google) so you login there and debug more productively.

**Comment by crioto** [comment]
@asanaliev for me these logs does not show any errors that can cause described behavior. Maybe we should ask @p1gmale0n to update p2p on these peers?

**Comment by asanaliev** [comment]
Seems p2p wasn't set up properly with last update on those old AWS peers. @p1gmale0n created new AWS instances. I created env over the following peers:

![image](https://cloud.githubusercontent.com/assets/7465404/16048651/b4070950-3276-11e6-8a61-1d65215718d3.png)

Could ping and ssh successfully between all of them.
