### ISSUE TITLE
After installed with win installer cannot ssh to container

### ISSUE THREAD

**Issue by btemir** [subutai-io/subos#370]
Can not ssh to container nor from hub nor from tray. To reproduce:
1. Download and run win dev installer
2. Launch to SS. About page:
![image](https://cloud.githubusercontent.com/assets/16958983/15798141/01643004-2a40-11e6-9ff4-fd1183364700.png)
3. Register peer to hub
4. Create environment (ceph environment was created)
5.Go to Environments-containers, click SSH button. Result:
![image](https://cloud.githubusercontent.com/assets/16958983/15798175/1b56c192-2a41-11e6-9965-bf77035268d3.png)
6. Go to Hub-Peer-Environments-Container and click SSH button.
![image](https://cloud.githubusercontent.com/assets/16958983/15798185/642a182e-2a41-11e6-8e13-9a3113fc85cc.png)
7. From tray: "Failed to run SSH because container is not ready".

LOGS:
1. karaf logs

[karaflogs2016-06-04 09-51-12.txt](https://github.com/subutai-io/subos/files/298710/karaflogs2016-06-04.09-51-12.txt)

2. Agent logs

[agent_log.txt](https://github.com/subutai-io/subos/files/298713/agent_log.txt)

3. p2p logs from rh
[p2p_log.txt](https://github.com/subutai-io/subos/files/298714/p2p_log.txt)

4. On host (Ubuntu-VMware -win)
![image](https://cloud.githubusercontent.com/assets/16958983/15798273/3fa207a2-2a44-11e6-91f4-4581cc7d40c3.png)

![image](https://cloud.githubusercontent.com/assets/16958983/15798278/58d106ec-2a44-11e6-85e5-aeac3b41dfb7.png)

**Comment by Dilshat** [comment]
According to karaf logs, SS is functioning OK.
Need to see on system/network level

**Comment by btemir** [comment]
On host:
Stopped P2P service  
![image](https://cloud.githubusercontent.com/assets/16958983/15798314/6d293e2e-2a45-11e6-93dc-571df6557a27.png)

Run p2p daemon (as Administrator)  
Try to ssh to container from tray
Having this output:

[p2p_daemon.txt](https://github.com/subutai-io/subos/files/298724/p2p_daemon.txt)

%Path% is :

![image](https://cloud.githubusercontent.com/assets/16958983/15798432/aedebf20-2a49-11e6-84b9-f38fbe516ef9.png)

**Comment by btemir** [comment]
Reinstalled on Lin-Win, Win-Win many times. Noted:
1. On Lin-VMWare-Win10: Environment created, IP addressed on host(x.x.x.245) and on RH(x.x.x.1) are assigned, network route exists. But host and rh can not ping each other using this addresses:
![image](https://cloud.githubusercontent.com/assets/16958983/15806994/64b24cae-2b62-11e6-9c51-8d98732c388c.png)
![image](https://cloud.githubusercontent.com/assets/16958983/15806998/973904d8-2b62-11e6-97d0-7666991f7c54.png)

On RH:
![image](https://cloud.githubusercontent.com/assets/16958983/15807013/e9c13752-2b62-11e6-9b7f-e85bd0e8186d.png)

![image](https://cloud.githubusercontent.com/assets/16958983/15807019/0e732fb0-2b63-11e6-82b5-8eb3471aa3b3.png)
part of ifconfig on RH: 
![image](https://cloud.githubusercontent.com/assets/16958983/15807025/3b92e8aa-2b63-11e6-945c-dfde67fff2e1.png)
 
2. On Win-VMware-Win IP address on for host not even assigned. 

Please let me know if something is needed (logs, actions, screenshots etc)

**Comment by btemir** [comment]
tray logs: (tray launched with SubutaiTray.exe -l 0)
[trace_05.06.2016.txt](https://github.com/subutai-io/subos/files/299430/trace_05.06.2016.txt)

[info_05.06.2016.txt](https://github.com/subutai-io/subos/files/299432/info_05.06.2016.txt)

[error_05.06.2016.txt](https://github.com/subutai-io/subos/files/299431/error_05.06.2016.txt)

**Comment by btemir** [comment]
p2p log (p2p run as p2p daemon):

[p2p_log.txt](https://github.com/subutai-io/subos/files/299433/p2p_log.txt)

**Comment by btemir** [comment]
on Win-VMWare-Win after manual run of  command showed got connected to container with ssh (but did not ping before this command so it can be not related)

on Lin-VMWare-Win after this command got "Integrated with" but no ping still

**Comment by crioto** [comment]
@btemir p2p fixed and needs to be tested

**Comment by btemir** [comment]
installed on lin-wmware-win. Registered peer, created environment. Trying to ssh to container from SS
![ssh](https://cloud.githubusercontent.com/assets/16958983/15814626/ad89ad82-2be9-11e6-895c-ff29981665dc.PNG)
host IP was not assigned:
![debug](https://cloud.githubusercontent.com/assets/16958983/15814677/03e9c888-2bea-11e6-9ef2-45b74111000f.PNG)
RH ifconfig:
![rh_ifconfig](https://cloud.githubusercontent.com/assets/16958983/15814754/77a8f884-2bea-11e6-895f-08f64cb22bfc.PNG)
RH p2p show 
![rh_debug](https://cloud.githubusercontent.com/assets/16958983/15814821/d265821a-2bea-11e6-9cc8-51df72e4b01e.PNG)

**Comment by btemir** [comment]
update: after some time on host:
![rh_debug updated](https://cloud.githubusercontent.com/assets/16958983/15814943/93dd1bba-2beb-11e6-9f7e-57af4e9f97e2.PNG)

**Comment by btemir** [comment]
p2p daemon output:
![daemon_1](https://cloud.githubusercontent.com/assets/16958983/15815149/d8847a28-2bec-11e6-9898-199751066b43.PNG)
![daemon_2](https://cloud.githubusercontent.com/assets/16958983/15815177/169dbd38-2bed-11e6-89d0-a2047f7b7803.PNG)

should TAP device be removed?

**Comment by crioto** [comment]
https://github.com/subutai-io/installers/issues/39

**Comment by btemir** [comment]
Had bug - TAP-Windows\bin was not added to user's %PATH% on WIn7. Fixed. Now have the same problem - TAP interface does not get IP Address
Output of p2p daemon:
[p2p_log.txt.txt](https://github.com/subutai-io/subos/files/308719/p2p_log.txt.txt)
netstat -r and ipconfig from host:
[netstat.txt.txt](https://github.com/subutai-io/subos/files/308722/netstat.txt.txt)

**Comment by btemir** [comment]
one problem cam be on localized Windows 7 - it has localized names if interfaces,   in interface name - in Russian letters. On win10 (Russian) interfaces are named "Ethernet0", "Ethernet 1" - and it works on configuration win-VMware-win/. But on Win 7 name of Tap interface is " Подключение по локальной сети 2", and u see in logs that symbols are strange (we need Unicode strings? and it works when i manually set up with this name/
On win-VMware-win on English versions or on Win 10 and Win8 ssh to container works.
But on lin-VMware-win ssh does not work on any Windows.

**Comment by btemir** [comment]
Situation on lin-VMWare-win. Win 10: ip address was assigned to TAP interface, but can not ping 
[ping.txt](https://github.com/subutai-io/subos/files/309111/ping.txt)

p2p daemon log 

[p2p_daemon.txt](https://github.com/subutai-io/subos/files/309120/p2p_daemon.txt)

**Comment by btemir** [comment]
more daemon log
[p2p_daemon_1.txt](https://github.com/subutai-io/subos/files/309556/p2p_daemon_1.txt)

**Comment by Dilshat** [comment]
@btemir please retest and close if fixed

**Comment by akarasulu** [comment]
Been 5 days @btemir is this issue fixed?

**Comment by btemir** [comment]
ssh to container does not work on windows 7 (on Rus - because of interface name, new network interface can get  IP address, but on English - IP address is set on container and host, but there is no ping)

**Comment by btemir** [comment]
Can ssh to container on Win7Emg, Win8, Win10 (In some cases need need to wait few minutes).

**Comment by asanaliev** [comment]
First several attempts failed on Windows 8 (physical). But can't reproduce again. Now ez-ssh is working.
