### ISSUE TITLE
IP address has not been changed

### ISSUE THREAD

**Issue by Ernisto** [subutai-io/subos#381]
Peer installed from scratch.

![image](https://cloud.githubusercontent.com/assets/13309012/15920713/fe6b64e2-2e3d-11e6-8efb-4f118d0aca04.png)

After Wi-Fi was disabled - IP address has not been changed

![image](https://cloud.githubusercontent.com/assets/13309012/15920789/93c41e44-2e3e-11e6-972d-97f787b902d3.png)

Also SS Console not accessible because of network disabled.

![image](https://cloud.githubusercontent.com/assets/13309012/15920827/f6393a96-2e3e-11e6-895a-03acb5fb98ed.png)

**Comment by tzununbekov** [comment]
@Ernisto don't you see that on your second screenshot you perform "detect" command before disconnecting network interface ("Reset adapter" output in terminal)? Also, address switching might take 5-20 seconds

**Comment by Ernisto** [comment]
It requires about ~20 seconds to obtain new IP. It works.
Thanks @tzununbekov
