### ISSUE TITLE
Ping works always, but SSH does not

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/subos#390]
_Moved from p2p issues: https://github.com/subutai-io/p2p/issues/153_

I created env using 3 peers: 
* Askat Peer (behind NAT)
* Sydyk Peer (behind NAT)
* AWS Germany (accessible directly)

![image](https://cloud.githubusercontent.com/assets/7465404/16173400/03caf08e-35c2-11e6-800b-db6d5c8f72d6.png)

I can successfully ping containers to each other (see ping-ssh-check.txt). But SSH fails between them (askat-peer-p2p-logs.txt). Seems this issue is mostly between peers behind NAT.

Note: for each command's response I waited ~20 sec. If there was none I typed Ctrl-C.

[ping-ssh-check.txt](https://github.com/subutai-io/p2p/files/321950/ping-ssh-check.txt)
[askat-peer-p2p-logs.txt](https://github.com/subutai-io/p2p/files/321949/askat-peer-p2p-logs.txt)

**Comment by asanaliev** [comment]
I tested a second time. From AskatPeer to SydykPeer two SSH commands completed successfuly, two others failed. 
```
root@2c86b132-1f04-467d-932f-14a732cfd61f:/# ssh root@172.29.73.3 date
^C
root@2c86b132-1f04-467d-932f-14a732cfd61f:/# ssh root@172.29.73.3 date
Sat Jun 18 23:16:47 EEST 2016
root@2c86b132-1f04-467d-932f-14a732cfd61f:/# ssh root@172.29.73.3 date
Sat Jun 18 23:17:10 EEST 2016
root@2c86b132-1f04-467d-932f-14a732cfd61f:/# ssh root@172.29.73.3 date
^C
```

But ping is always successful between all peers (i.e. peer containers).

Also I tested from AWS Peer. Failed once only - to SydykPeer:
```
root@3306aa07-f315-498c-b6c8-bde6bcb8d24c:/# ssh root@172.29.73.3 date
^C
root@3306aa07-f315-498c-b6c8-bde6bcb8d24c:/# ssh root@172.29.73.3 date
Sat Jun 18 23:26:12 EEST 2016
root@3306aa07-f315-498c-b6c8-bde6bcb8d24c:/# ssh root@172.29.73.3 date
Sat Jun 18 23:26:20 EEST 2016
root@3306aa07-f315-498c-b6c8-bde6bcb8d24c:/# ssh root@172.29.73.3 date
Sat Jun 18 23:26:26 EEST 2016
```

[check-2-from-askat-peer.txt](https://github.com/subutai-io/p2p/files/321956/check-2-from-askat-peer.txt)
[check-2-from-aws-peer.txt](https://github.com/subutai-io/p2p/files/321955/check-2-from-aws-peer.txt)
[aws-peer-p2p-logs.txt](https://github.com/subutai-io/p2p/files/321954/aws-peer-p2p-logs.txt)

**Comment by samsonbek** [comment]
I had same situation with Sydyk's peer, i have environment with 4 peers (1 Aknet NATed, 1 Megaline NATed, 1 AWS , 1 Google). For all peers except 'Megaline NATed' both ssh and ping worked every time, but for Sydyk's peer (Megaline NATed) ssh was sometime working, sometime it was hanging in waiting state.

**Comment by soffokl** [comment]
172.21.205.2 is local container, and ssh works very fast.
172.21.205.4 and 172.21.205.3 remote container, and ssh works slow and not always.
```
(amd64)root@1cb34706-d3dc-477c-be29-02cc6a0e0054:/# time ssh 172.21.205.2 date
Sun Jun 19 07:24:43 EEST 2016

real	0m0.078s
user	0m0.012s
sys	0m0.000s
(amd64)root@1cb34706-d3dc-477c-be29-02cc6a0e0054:/# time ssh 172.21.205.4 date
Sun Jun 19 07:24:54 EEST 2016

real	0m7.857s
user	0m0.012s
sys	0m0.000s
(amd64)root@1cb34706-d3dc-477c-be29-02cc6a0e0054:/# time ssh 172.21.205.3 date
Sun Jun 19 07:25:13 EEST 2016

real	0m3.241s
user	0m0.008s
sys	0m0.004s
(amd64)root@1cb34706-d3dc-477c-be29-02cc6a0e0054:/# time ssh 172.21.205.3 date
Sun Jun 19 07:25:29 EEST 2016

real	0m3.119s
user	0m0.012s
sys	0m0.000s
(amd64)root@1cb34706-d3dc-477c-be29-02cc6a0e0054:/# time ssh 172.21.205.3 date
Sun Jun 19 07:25:37 EEST 2016

real	0m3.154s
user	0m0.012s
sys	0m0.000s
(amd64)root@1cb34706-d3dc-477c-be29-02cc6a0e0054:/# time ssh 172.21.205.3 date
^C

real	0m38.614s
user	0m0.004s
sys	0m0.000s
(amd64)root@1cb34706-d3dc-477c-be29-02cc6a0e0054:/# 
```

About pings, if set default packet size 56 bytes, pings work. But this shows that small packets works. 
Not all packets in standard network traffic have small size. 
And if we changing size of ping packed to standard MTU size for TCP (1500 bytes) we can see that we have lots of losing packets. 

```
(amd64)root@1cb34706-d3dc-477c-be29-02cc6a0e0054:/# ping 172.21.205.3 -s1500
PING 172.21.205.3 (172.21.205.3) 1500(1528) bytes of data.
1508 bytes from 172.21.205.3: icmp_seq=1 ttl=64 time=289 ms
1508 bytes from 172.21.205.3: icmp_seq=2 ttl=64 time=315 ms
1508 bytes from 172.21.205.3: icmp_seq=11 ttl=64 time=201 ms
1508 bytes from 172.21.205.3: icmp_seq=12 ttl=64 time=264 ms
1508 bytes from 172.21.205.3: icmp_seq=15 ttl=64 time=234 ms
^C
--- 172.21.205.3 ping statistics ---
18 packets transmitted, 5 received, 72% packet loss, time 17082ms
rtt min/avg/max/mdev = 201.806/261.111/315.378/39.993 ms
(amd64)root@1cb34706-d3dc-477c-be29-02cc6a0e0054:/# 
```

**Comment by soffokl** [comment]
Tested on 2 Megaline peers, both behind NAT.

**Comment by crioto** [comment]
```
p2p debug
DEBUG INFO:
Number of gouroutines: 17
Instances information:
Hash: INTERNAL_DEV_TEST_SWARM_0652
ID: 0f084307-35de-11e6-8228-022d0fae0f03
Interface vptp1, HW Addr: 06:9f:38:82:5d:ec, IP: 10.10.10.1
Peers:
	--- 0f115974-35de-11e6-8203-022d0fae0f03 ---
		HWAddr: 06:6b:9a:0e:5d:4d
		IP: 10.10.10.245
		Endpoint: 54.93.164.238:47139
		Peer Address: 158.181.233.198:53197
		Proxy ID: 21
	--- End of 0f115974-35de-11e6-8203-022d0fae0f03 ---
```

SSH tries:
```
ssh ubuntu@10.10.10.245
ubuntu@10.10.10.245's password: 
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Sun Jun 19 11:24:27 KGT 2016

  System load:  0.0               Processes:           82
  Usage of /:   18.0% of 6.75GB   Users logged in:     1
  Memory usage: 11%               IP address for eth0: 192.168.0.192
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

138 packages can be updated.
68 updates are security updates.

Last login: Mon Jun 13 13:23:34 2016
```
10/10 SSH connections was established.

**Comment by soffokl** [comment]
Waiting fixes in https://github.com/subutai-io/p2p/issues/153

**Comment by tzununbekov** [comment]
@asanaliev could you try to reproduce it again and update us with results?

**Comment by Dilshat** [comment]
We can close this issue, if needed analog issues exist in p2p repo
