### ISSUE TITLE
Enable P2P downloads of large public artifacts

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#493]
Right now embedded Kurjun downloads CDN artifacts from from nearest CDN nodes. After implementing #486 we should enable peer-to-peer downloads of large public artifacts from all CDN nodes and other embedded Gorjun instances. Implementing digital signatures is a requirement as well for this feature: #492.

**Comment by soffokl** [comment]
Moved to https://github.com/subutai-io/gorjun/issues/23
