### ISSUE TITLE
Network reconfiguration when roaming should induce pre-emptive heartbeat

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#498]
Right now after the network changes or a machine wakes up to re-initialize it's network a manual heartbeat is required to show the peer as online. Otherwise we have to wait a long time. It would be nice if when subos detects these changes it makes the management server induce a peer heartbeat.

**Comment by soffokl** [comment]
When network have any changes Agent sends heartbeat with new network configuration to Management. Management can use this information to update HUB.

**Comment by akarasulu** [comment]
It should then be an easy trigger. @Dilshat maybe @eabyshev can knock this one out easily?

**Comment by eabyshev** [comment]
done
