### ISSUE TITLE
Review wiki page about Subutai Agent workflow

### ISSUE THREAD

**Issue by soffokl** [subutai-io/subos#568]
https://github.com/subutai-io/subos/wiki/Subutai-Agent-workflow

**Comment by akarasulu** [comment]
@soffokl please review for comments with AOK in it.

**Comment by soffokl** [comment]
done

**Comment by akarasulu** [comment]
Got a create new page from this link above. Maybe you moved it?

**Comment by soffokl** [comment]
Yeah, Subutai Agent now have own repo: https://github.com/subutai-io/agent/wiki/Subutai-Agent-workflow
