### ISSUE TITLE
Impossible to destroy container if consistency check is not valid

### ISSUE THREAD

**Issue by larenso** [subutai-io/subos#60]
Impossible to destroy container if consistency check is not valid, log file is attached
1) tried to create container, but it somehow created no consistent containers
2) couldn't destroy them
[output.txt](https://github.com/subutai-io/subos/files/161028/output.txt)

**Comment by soffokl** [comment]
@larenso This problem was fixed few days ago. Do you using latest build?
https://github.com/subutai-io/base/issues/155

**Comment by soffokl** [comment]
Duplicate of subutai-io/base#155
