### ISSUE TITLE
Update NGINX gateway rules for domain when containers are started and stopped 

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#626]
Starting and stopping a container does not change the peer’s HTTP request routing via NGINX to the container. When a container in the cluster is stopped NGINX is still trying to route HTTP requests to it but the container is down and there is no web service there to handle the request and for this reason we are getting the 502 “Bad Gateway” error. 

1. The NGINX proxy (gateway) in SS, MUST be modified to add/remove routing rules when a container is stopped (remove) and started (add). This is a proper action that should be taken to give a clear message. We do not know how long the node will be down, whether it is caused by the user or an error but we need to remove the route so external load balancers can respond appropriately. (edited)

The best way to handle this is to enable CLI if not already capable to add and remove NGINX gateway routes for a domain when the container is turned on and off using the LXC hook scripts.

**Comment by tzununbekov** [comment]
@akarasulu by default, Nginx's routing policy includes backend [health checks](http://nginx.org/en/docs/http/load_balancing.html#nginx_load_balancing_health_checks), so stopping/starting containers shouldn't affect service availability

**Comment by akarasulu** [comment]
Is it working properly if the container is down and NGINX is still trying to route to it. Why do we get the 502?

**Comment by tzununbekov** [comment]
If there are no available containers left, but requests are still going to domain configured on this peer, Nginx will return 502 error and this is normal behavior

**Comment by akarasulu** [comment]
Ok but with this behavior (502 response), does Route53 think the node is down? 

Also I is the 502 response returned immediately?

**Comment by akarasulu** [comment]
I think the problem here is that the peer knows that no routable containers are up yet Route53 is still routing to the peer's containers. I think Route53 then needs to be updated when containers at a peer are down.

**Comment by tzununbekov** [comment]
> does Route53 think the node is down?
it depends on Route53 health checks configuration - it should expected response code 200 to consider route as available

> is the 502 response returned immediately
relatively. Nginx first waits for container's response and if there is no response in time, then 502 is returned. But this is timeout shouldn't be a problem for route53 health checks

**Comment by tzununbekov** [comment]
looked into current route53 configurations: it expects status code 200 in response from peer and if it is not getting it 3 times in a row with 10 seconds interval, route being excluded from dns record set

**Comment by tzununbekov** [comment]
I guess this issue may be closed, there is nothing to change in Nginx
