### ISSUE TITLE
Single container environment on monster peer not allowing SSH even with keys

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#627]
> ssh root@10.40.3.1 -p 10003 -i '/Users/akarasulu/.ssh/id_rsa' 
mbp:~ akarasulu$ ssh root@10.40.3.1 -p 10003 -i '/Users/akarasulu/.ssh/id_rsa' 
ssh: connect to host 10.40.3.1 port 10003: Connection refused

Looks like something wrong with the tunnel.

**Comment by soffokl** [comment]
@akarasulu There is no tunnels in this process. 
Connection was refused. 
You need to check if 10.40.3.1 pingable at all from your host.
And check if container started.

**Comment by akarasulu** [comment]
Tried it and connectivity is there: IP changed though but the same problem persists. Please see below. 

> mbp:~ akarasulu$ ssh root@10.188.28.1 -p 10003 -i '/Users/akarasulu/.ssh/id_rsa' 
ssh: connect to host 10.188.28.1 port 10003: Connection refused
mbp:~ akarasulu$ ping 10.188.28.1
PING 10.188.28.1 (10.188.28.1): 56 data bytes
64 bytes from 10.188.28.1: icmp_seq=0 ttl=64 time=164.041 ms
64 bytes from 10.188.28.1: icmp_seq=1 ttl=64 time=164.876 ms
^C
--- 10.188.28.1 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 164.041/164.459/164.876/0.417 ms

**Comment by akarasulu** [comment]
Yup confirmed that ssh was not installed or running.
