### ISSUE TITLE
Investigate option to expose website behind NAT with p2p

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/subos#628]
Requirement:
Hub should be able to expose NAT'ed websites from user's peers to the Web with "white" IP and 80/443 port

We need to investigate the way where we make helper nodes the part of target swarms to forward requests from outside network to p2p tunnels

**Comment by tzununbekov** [comment]
After quick tests, looks like most feasible approach is to have special p2p swarm which will connect NAT'ed Resource host with Hub helpers (or some sort of Gateway peers). This scheme has following advantages:
 - the number of required p2p swarms on Helper node is not depends on number of environments - it is always equal to number of target Resource hosts. During tests I've created about 70 p2p interfaces on single "modest" peer without visible problems, although, didn't tested it under load
 - comparing to ssh tunnels, p2p tunnel provides access not to the single port, but to the whole host which is also more efficient in case when multiple ports/protocols needs to be forwarded
 - described approach doesn't require significant architectural changes in existing Subutai components; it will require just a specific commands set of existing CLI        
 - having dedicated p2p swarm with Helpers and peers will give us more possibilities in future for such features as backup syncing, live migration, etc. 

CLI commands sequence and some diagram to describe all steps of this approach will be added here soon

**Comment by tzununbekov** [comment]
1) create p2p peer on target RH:
`subutai p2p -c <dev name> <swarm id> <key> <ttl> <rh swarm ip> 0-65535`

here, in "dev name" would be useful to put helper node id to identify connection destination by its name

2) add cdn node to swarm:
`subutai p2p -c <dev name> <swarm id> <key> <ttl> <helper swarm ip> 0-65535`

here, in "dev name" would be useful to put target host id to identify connection destination by its name

3) create rev proxy domain on rh, add containers:
`subutai proxy add <id> -d <domain>`
`subutai proxy add <id> -h <container ip>`

4) create rev proxy domain on cdn, add rh:
`subutai proxy add <id> -d <domain>`
`subutai proxy add <id> -h <rh swarm ip>`

Important thing that should be noted here - possible subnet conflicts; hub must add new networks with consideration of existing ones.
At this point we should start communicating with Hub team to prepare stage platform for tests.
@akarasulu @asanaliev please comment on this

**Comment by akarasulu** [comment]
> We need to investigate the way where we make helper nodes the part of target swarms to forward requests from outside network to p2p tunnels

@soffokl made an point about **NOT** using Hub Helpers to expose endpoints. I think he had some concerns about the additional bandwidth potentially interfering with the operation of other critical infrastructure running on the Hub Helpers (i.e. CP nodes for DHT).

**Comment by akarasulu** [comment]
> After quick tests, looks like most feasible approach is to have special p2p swarm which will connect NAT'ed Resource host with Hub helpers (or some sort of Gateway peers).

I'm not fully understanding the configuration here especially with the use of term `swarm`. A swarm is a dynamic grouping of authenticated and authorized peers that provide resources for a specific environment. Each environment has its own swarm with changing symmetric key to provide network encryption. So for me a `special p2p swarm` is a grouping of peers that have been authorized and authenticated to provide resources for an environment.

If we are talking about the same thing, then your `special p2p swarm` might actually violate isolation and present security problems. I still need to read further to understand how the NAT'd RHs will be connected to these peers.

**Comment by tzununbekov** [comment]
> @soffokl made an point about NOT using Hub Helpers to expose endpoints. I think he had some concerns about the additional bandwidth potentially interfering with the operation of other critical infrastructure running on the Hub Helpers (i.e. CP nodes for DHT).

It is an implementation details that are not so critical now

> I'm not fully understanding the configuration here especially with the use of term swarm

For me, `swarm` is a group of hosts united in the same p2p network

**Comment by akarasulu** [comment]
>  - the number of required p2p swarms on Helper node is not depends on number of environments - it is always equal to number of target Resource hosts. During tests I've created about 70 p2p interfaces on single "modest" peer without visible problems, although, didn't tested it under load

Again I'm a bit lost on the swarm terminology. However I think I understand what you are saying: the number of interfaces that will be needed **NOT** a function of the number of environments that exist but by the number of RHs correct?

Also please correct me if I am wrong, but the RHs that you are referring to (which will use this pool of exposed gateway peers to expose ports) are ones that are NAT'd correct? 

> - comparing to ssh tunnels, p2p tunnel provides access not to the single port, but to the whole host which is also more efficient in case when multiple ports/protocols needs to be forwarded

👍  

I agree this is a **BIG** plus. The SSH tunnel is not viable for general use or as a long term solution. It might still be kept for ad hoc sysadmin use in special circumstances.

> - described approach doesn't require significant architectural changes in existing Subutai components; it will require just a specific commands set of existing CLI        

👍 

> - having dedicated p2p swarm with Helpers and peers will give us more possibilities in future for such features as backup syncing, live migration, etc. 

I'm still a bit lost on the dedicated p2p swarm concept. Do you mean a pool of accessible peers specifically tasked with routing traffic to inaccessible NAT'd RHs? 

The way you use `swarm` is confusing me and I think we need clarification and synchronization on the terminology to prevent miscommunication.

**Comment by akarasulu** [comment]
> For me, `swarm` is a group of hosts united in the same p2p network

Yes but let me add to that: a swarm is authenticated and authorized to join the network which uses a cycling shared secret (symmetric key). 

Our goal is to expose access from the Internet to services and applications of SS environments running inside inaccessible peer RHs (NAT'd or for other reasons). All environments have their own `swarm` with their own shared secret which periodically cycles correct? What I am having trouble understanding is how you can have one common shared swarm connecting other swarms without it becoming a security nightmare.

I'm presuming you mean to have a pool of peers not in a common swarm together but just peers. Members of these peers can join the swarm of environments (with no direct access RHs) to expose container ports correct?

**Comment by akarasulu** [comment]
> 1) create p2p peer on target RH:
`subutai p2p -c <dev name> <swarm id> <key> <ttl> <rh swarm ip> 0-65535`
here, in "dev name" would be useful to put helper node id to identify connection destination by its name

Where would this be executed? It adds a `p2p peer`? What is this `target RH`? Please be explicit.

> 2) add cdn node to swarm:
`subutai p2p -c <dev name> <swarm id> <key> <ttl> <helper swarm ip> 0-65535`
here, in "dev name" would be useful to put target host id to identify connection destination by its name

Again please be explicit. I take it this process is connecting an environment's inaccessible NAT'd RH to one of the RH's of the peers in the dedicated and exposed peer pool?

> 3) create rev proxy domain on rh, add containers:
`subutai proxy add <id> -d <domain>`
`subutai proxy add <id> -h <container ip>`

This creates a vhost for proxying HTTP traffic? 

> 4) create rev proxy domain on cdn, add rh:
`subutai proxy add <id> -d <domain>`
`subutai proxy add <id> -h <rh swarm ip>`

Can you explain why we have to do this on both the NAT'd peer and the accessible pool peer?

> Important thing that should be noted here - possible subnet conflicts; hub must add new networks with consideration of existing ones.

Can you elaborate and provide example how this conflict can occur?

**Comment by tzununbekov** [comment]
> However I think I understand what you are saying: the number of interfaces that will be needed NOT a function of the number of environments that exist but by the number of RHs correct?

> Also please correct me if I am wrong, but the RHs that you are referring to (which will use this pool of exposed gateway peers to expose ports) are ones that are NAT'd correct?

Both correct

> Do you mean a pool of accessible peers specifically tasked with routing traffic to inaccessible NAT'd RHs?

Yes, the same peers that will expose Http(s) services from NAT'ed RHs

> All environments have their own swarm with their own shared secret which periodically cycles correct? What I am having trouble understanding is how you can have one common shared swarm connecting other swarms without it becoming a security nightmare.

Correct, each environment has it's own isolated p2p swarm, but Resource Hosts where environments are located has access to those swarms and our "special" swarm (need to name it somehow) provides an access to RH.

> I'm presuming you mean to have a pool of peers not in a common swarm together but just peers. Members of these peers can join the swarm of environments (with no direct access RHs) to expose container ports correct?

Need to clarify it. Actually, general idea is simple - create p2p network which will connect NAT'ed RH with Gateway node. All other features as HTTP forwarding will be implemented on application layer on the top of this p2p network using reverse proxy, port mapping, etc.

> Where would this be executed? It adds a p2p peer? What is this target RH? Please be explicit.

Yes, it adds p2p peer. "Target RH" - is RH which needs to be exposed to the network. 

> I take it this process is connecting an environment's inaccessible NAT'd RH to one of the RH's of the peers in the dedicated and exposed peer pool?

It connects "target RH" to the Gateway node.

> This creates a vhost for proxying HTTP traffic?

Yes

> Can you explain why we have to do this on both the NAT'd peer and the accessible pool peer?

We have to do this on both "sides" to forward HTTP traffic for all environments of one peer through the single p2p connection. Let's consider following scenario:   
- we have aaa.com and bbb.com websites in two different environments on one NAT'ed peer. 
- we are creating vhosts for those websites on NAT'ed peer and forward traffic to the containers according to the domain name
- we are creating p2p connection between this peer and Gateway node
- we are adding vhost configuration for aaa.com and bbb.com on Gateway node reverse proxy and forward all traffic through the single p2p connection to the NAT'ed peer where second reverse proxy will route it to the final destination.

This way we can have single p2p connection for multiple environments    

> Can you elaborate and provide example how this conflict can occur?

Peers can already contain multiple p2p networks with different subnets, so "special" p2p swarm should not take those subnets if they already exist

**Comment by tzununbekov** [comment]
## Benchmark results for different configurations:

- benchmark utility: sysbench
- backend application: mysql
- protocol: tcp 
- reverse proxy: nginx

Command line: 
```
sysbench --test=oltp --oltp-table-size=1000000 --mysql-db=test --mysql-user=**** --mysql-password=**** --mysql-host=<ip> --mysql-port=<port> --max-time=<period> --oltp-read-only=on --max-requests=0 --num-threads=2 run
```

### Control setup, LAN connection:
sysbench - (lan) -> peer : nginx -> container : mysql

![image](https://cloud.githubusercontent.com/assets/13515865/21847226/ef65b6dc-d824-11e6-9abc-367a5c71b183.png)

### SSH tunnel
#### via Hub Helper node
sysbench - (wan) -> helper - (ssh tunnel) -> peer : container : mysql

![image](https://cloud.githubusercontent.com/assets/13515865/21847407/fc427be6-d825-11e6-9b28-d9579be8bf3f.png)

#### via local Helper
sysbench - (lan) -> helper - (ssh tunnel) -> peer : container : mysql

![image](https://cloud.githubusercontent.com/assets/13515865/21847759/cc41eac4-d827-11e6-9043-2bab4e57a3ff.png)

### P2P connection
#### via Hub Helper
sysbench - (wan) -> helper - (p2p) -> peer : nginx -> container : mysql

![image](https://cloud.githubusercontent.com/assets/13515865/21847889/7f1a83e0-d828-11e6-9444-e1fc0310ac65.png)


#### via local Helper
sysbench - (lan) -> helper - (p2p) -> peer : nginx -> container : mysql

![image](https://cloud.githubusercontent.com/assets/13515865/21847957/bbf51b54-d828-11e6-8f02-65c0ac91e7fa.png)

### Conclusion
As it seen in sysbench results, ssh tunnel shows better performance comparing to p2p, but it looks like p2p has some optimization problem which makes it fully consume one core of CPU even without load; Mike was informed about it. Also, tests showed obvious thing - in scenario, where Gateway node located not in LAN, but in the Internet, performance dramatically drop by hundred times because of network latency. This should remind us once again that NAT exposing feature (in a proposed approach) is very limited in terms of performance.

**Comment by akarasulu** [comment]
With all WAN Helper cases what was the network distance?

**Comment by tzununbekov** [comment]
Peer located on my laptop, helper - AWS instance in Frankfurt
Latency about 100ms and >15 hops between them

**Comment by akarasulu** [comment]
@tzununbekov https://github.com/subutai-io/p2p/issues/242#issuecomment-273505415

**Comment by tzununbekov** [comment]
Performance and system load is much better after latest fix. CPU utilization is not jumping over 30% under load which is ok
![image](https://cloud.githubusercontent.com/assets/13515865/22101990/eeac5692-de5f-11e6-8c22-4c2f3c95d67b.png)

**Comment by akarasulu** [comment]
Which configuration is this for above? There were a couple different confs with p2p. Also can you state old value before performance fix and new value now?

**Comment by tzununbekov** [comment]
Latest result is for p2p tunnel via local peer (to exclude network high latency). Key values to compare:
                                         without fix                    with fix
 total queries:                     33568                         50048
 total num of events            2098                           3128
 avg req time, ms                  57                               38

But more important is CPU load during tests - constantly >100% before fix and <30% after

**Comment by tzununbekov** [comment]
https://github.com/subutai-io/agent/issues/55
