### ISSUE TITLE
Put a copy of PGP key inside container

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/subos#630]
To support issue https://github.com/subutai-io/base/issues/1630 we need to put a copy of container PGP keyring inside the container fs.
Also we need to have **wget** or **curl** tool inside master template so that a bash script can use it to access management REST endpoints from within a container.

**Comment by soffokl** [comment]
A key now stored inside a container `/etc/subutai/key`

**Comment by akarasulu** [comment]
@Dilshat @soffokl did we not abandon this approach?

**Comment by akarasulu** [comment]
Looks like we will be reverting this change since it violates some of security principles and a different approach was considered. This change needs to be reverted soon after confirmation from @Dilshat.
