### ISSUE TITLE
Management container host is not starting up after shutdown

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#633]

**Comment by soffokl** [comment]
@akarasulu how do you shutdown it?

**Comment by akarasulu** [comment]
It was a graceful shutdown of the host OS reboot or shutdown -h now. Same issued on RH.

**Comment by akarasulu** [comment]
Let me test more before you waste time on it. I'll get back to you.

**Comment by akarasulu** [comment]
This is looking like a karaf startup problem. I rebooted the RH from inside. Then when it came back up, I saw that java was not running but the container is up.

> (amd64)root@rh1483477395:~# ps -eaf | grep java
root      1892  1706  0 15:40 pts/0    00:00:00 grep --color=auto java
(amd64)root@rh1483477395:~# subutai list -c
CONTAINER
---------
management

This points to an issue with starting up java and karaf inside the container. 

@Dilshat please take a look at what could cause this.

**Comment by Dilshat** [comment]
please attach Karaf logs, i can not reproduce this

**Comment by soffokl** [comment]
It's not reproducible
