### ISSUE TITLE
[Howto] How do I increase the size of the btrfs disk after installation?

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#634]

**Comment by akarasulu** [comment]
@p1gmale0n Can you create a how to guide in our wiki for this?

**Comment by akarasulu** [comment]
You do this yet ?

**Comment by soffokl** [comment]
https://github.com/subutai-io/subos/wiki/How-do-I-increase-the-size-of-the-btrfs-disk-after-installation%3F
