### ISSUE TITLE
Static network configuration for peers

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#635]
I know we've make the configuration of the peer dynamic and even made it so we can gracefully handle roaming. However in a server installation no one wants to deal with DHCP. Administrators will want to configure peers and resource hosts statically. We need to provide an option for this.

For the short term a just a simple how to guide to setup static networking and stop the initbr script might be the enough for the peer/rh wan interface.

**Comment by soffokl** [comment]
Issue moved to [subutai-io/snap #41](https://github.com/subutai-io/snap/issues/41) via [**ZenHub**](https://www.zenhub.com/)
