### ISSUE TITLE
Cli command for getting info about lxc container (cpu, ram and etc.)

### ISSUE THREAD

**Issue by eabyshev** [subutai-io/subos#636]
It will be nice to have such cli command to check container info like this:
![screenshot from 2017-01-11 11 06 47](https://cloud.githubusercontent.com/assets/16954849/21836539/24aeaefa-d7f0-11e6-996f-baeaf6541501.png)

**Comment by bmullan** [comment]
**lxc-info** is an lxc v1 syntax.  

**lxc info** is the lxd (lxc v2) syntax.

**Comment by soffokl** [comment]
we already have binding for that: `subutai info quota`
