### ISSUE TITLE
Do we have a container network quota?

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#637]
I know we have quota dimensions for disk, RAM and CPU but do we have one for network? 

I'm presuming no. If yes, did we handle monthly transfer quota and a sustained throughput quota?

**Comment by tzununbekov** [comment]
@akarasulu We have quota for container's network bandwidth (https://github.com/subutai-io/subos/wiki/Quota), but we don't handle monthly transfer quota and I don't think, that agent should do that - it is more high-level issue for SS, agent providing all required commands and information for that

**Comment by akarasulu** [comment]
Thanks @tzununbekov.
