### ISSUE TITLE
Does scp to container degrade to password when your keys are installed?

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#640]
SSH to container in env no problem:

> akarasulu@fermi:~$ ssh -p 10007 root@10.52.158.1 uname -a
Linux dev 3.19.0-47-generic #53-Ubuntu SMP Mon Jan 18 14:02:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Try to use SCP to container degrades to password:

> akarasulu@fermi:~$ scp foobar.txt -P 10007 root@10.52.158.1:
root@10.52.158.1's password: 

Is this happening to anyone else?

**Comment by soffokl** [comment]
@akarasulu works fine for me. 

Your problem could be related to ugly scp syntax. Try to place `-P 10007` before filename. 
`scp -P 10007 foobar.txt root@10.52.158.1:/root`
