### ISSUE TITLE
Intermittent problems with hostnamectl

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/subos#641]
When changing RH hostname via **hostnamectl**, sometimes it works and sometimes it fails:

> 2017-01-18 02:50:40,597 | DEBUG | tp583124396-5680 | CommandProcessor                 | 163 - io.subutai.core.executor.impl - 4.0.14.SNAPSHOT | Sending:
> {
>   "request": {
>     "type": "EXECUTE_REQUEST",
>     "id": "35DB4AFC8D018B164D9FC704694EBFFFE6134FAE",
>     "commandId": "2788006b-87e9-46fb-8ab4-373f093fbe64",
>     "workingDirectory": "/",
>     "command": "hostnamectl set-hostname daMan ",
>     "stdOut": "RETURN",
>     "stdErr": "RETURN",
>     "runAs": "root",
>     "timeout": 30,
>     "isDaemon": 0
>   }
> }
> 2017-01-18 02:50:41,028 | DEBUG | tp583124396-5710 | CommandProcessor                 | 163 - io.subutai.core.executor.impl - 4.0.14.SNAPSHOT | Response: ResponseImpl[type=EXECUTE_RESPONSE,id=35DB4AFC8D018B164D9FC704694EBFFFE6134FAE,commandId=2788006b-87e9-46fb-8ab4-373f093fbe64,pid=0,responseNumber=1,stdOut=<null>,stdErr=Could not set property: Failed to write machine info: Read-only file system
> ,exitCode=1]

**Comment by soffokl** [comment]
We decided to use `subutai hostname` binding for changing hostname, it works well.
