### ISSUE TITLE
Migrate management template to the ubuntu16 parent

### ISSUE THREAD

**Issue by soffokl** [subutai-io/subos#642]
As a part of migrating all templates to the latest Ubuntu version we need to reconfigure Jenkins server to build Management template based on ubuntu16 template.

**Comment by p1gmale0n** [comment]
blocked by #643

**Comment by p1gmale0n** [comment]
subutai-dnsmasq - removed. currently we does not need dhcp server on management container.
subutai-influxdb - changed to official influxdb deb. upgraded to 1.1 version.
gorjun - ubuntu16 package have `gorjun-local` name.

**Comment by p1gmale0n** [comment]
new packages is ready (#643).

**Comment by p1gmale0n** [comment]
done in https://github.com/subutai-io/base/pull/1747
