### ISSUE TITLE
Can Subutai Social Hub be installed for a private use for something like Education

### ISSUE THREAD

**Issue by bmullan** [subutai-io/subos#644]
I looked but can't find if Subutai Social Hub can be installed for a private use like in Education.

Schools/Education might benefit from Subutai Social but due to security aspects probably would have to host their own Subutai Social Hub to register student/teachers/parents into.

Is this possible?   

Thanks
Brian

**Comment by asanaliev** [comment]
Hi, Brain!

Yes, that is possible. This would be a useful and interesting opportunity for us too to get some feedback from that educational direction.

**Comment by asanaliev** [comment]
This is not strange that you could not find any proper documentation about installing your own Subutai Hub. We have not published yet any information about it.

Some features are in active development and in beta version still. We have to complete them and do proper testing before offering to our users.

Meantime, you might evaluate the existing available features on the Hub itself. Of course, we would love to get more feedback from your and your colleagues. This is a great opportunity for us to improve the product.

**Comment by bmullan** [comment]
Ok... now I understand thanks.

FYI I did put a mention of Subutai Social onto the LXD sub-reddit that I
moderate on Reddit.

https://www.reddit.com/r/LXD/

Brian
