### ISSUE TITLE
Prepare container upgrade mechanism

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/subos#94]
We need to implement simple mechanism that will enable user to upgrade containers in existing environments. It might be "Update is available" notification message in UI with button bind to apt upgrade command in environment. In this case using apt cache on peer makes sense.

**Comment by akarasulu** [comment]
This is a really nice feature for us to have.

**Comment by tzununbekov** [comment]
Standard `apt upgrade` way seems working inside containers, nginx re-configured to work as cache for Ubuntu apt repository, CLI updated to change apt source list inside the c ontainers. Further steps should be coordinated with core-team
